### ISSUE TITLE
Boltz clones

### ISSUE THREAD

**Issue by pseudozach** [cointastical/Exchanges-With-LN#3]
There are boltz clones that allow submarine swaps between LN and different chains:
https://www.marduk.exchange/ - LN to/from RBTC/SOV/xUSD
https://www.lnswap.org/ - LN to/from STX/USDA

**Comment by cointastical** [comment]
Thank you for the submission.

Those two have been added to the list.

**Comment by pseudozach** [comment]
oops they look incorrect. it's the other way. lnswap - stacks. marduk - rsk

**Comment by cointastical** [comment]
Doh!!!   Thank for your doing a check and for notifying me. 

Fixed.
