### ISSUE TITLE
River Financial requires KYC

### ISSUE THREAD

**Issue by brijananand** [cointastical/Exchanges-With-LN#4]
Hi,

On the readme document [River Financial](https://river.com/) is listed as [NO KYC]. However, during sign up the user has to provide their KYC information including the last 4 digits of their SSN. This associates their account with their actual identity. I think this should be updated to remove the [NO KYC] tag. See below page for reference, without entering those details a user cannot access their account, exchange or profile. 

![image](https://user-images.githubusercontent.com/567661/149635012-aaf427f2-9a11-4399-b74e-783968313d3a.png)

**Comment by cointastical** [comment]
Fixed.  Closing ticket.
